name: Remote URL Fetch One-Time
on: 
  workflow_dispatch: # This adds a manual "Run" button in your browser

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Fetch File Directly From URL
        run: |
          # Replace URL below with actual link;
          # Replace OUT with directory and file name.
          
          #URL="https://github.com/ogatatsu/PMW3360-Module/raw/master/Datasheets/"
          #URL+="PMS0058-PMW3360DM-T2QU-DS-R1.50-26092016._20161202173741.pdf"
          
          OUT="Reference/Sensor Datasheet/PMW3360DM-T2QU-DS-R1.50-26092016.pdf"
          
          curl -L "$URL" -o "$OUT"

      - name: Commit File to GitHub
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@://github.com"
          git add .
          git commit -m "Fetch remote file via GitHub Actions cloud" || exit 0
          git push
