name: Remote URL Fetch One-Time
on: 
  workflow_dispatch: # This adds a manual "Run" button in your browser

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Fetch File Directly From URL
        run: |
          # REPLACE THE URL BELOW WITH YOUR ACTUAL LINK
          # REPLACE "my-file.zip" WITH WHAT YOU WANT TO NAME THE FILE
          curl -L "CAESeQHrOzAV3JcGisCp9-jcIxVwkBKnEbGBPbp22CIgcGz9N3HnsovzY7cof4mw8mJY2hGdcx5u44Wb0er6woszVrbg6RN9l8EqXoAmVLcs24nzKegBX26I_nPBl6UXeOlvHORH2RfNWan8xWmqZCmil6TbWb4s-FweoX4" -o "PMW3610DM-SUDU.pdf"

      - name: Commit File to GitHub
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@://github.com"
          git add .
          git commit -m "Fetch remote file via GitHub Actions cloud" || exit 0
          git push
